
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setDate(); setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JLabel();
        nonis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        b5 = new javax.swing.JLabel();
        tptlahir = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        b6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        tgllahir = new com.toedter.calendar.JDateChooser();
        b10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 18)); // NOI18N
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM MALANG ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 0, 460, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("THE REAL INFORMATIC SCHOOL\n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 20, 240, 40);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setLayout(null);

        tabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "JenisKelamin", "Kelas", "Email", "Alamat", "Tempat Lahir", "Tanggal Lahir"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 620, 440);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(350, 130, 640, 460);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ISIAN DATA SISWA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 1, 12))); // NOI18N
        jPanel1.setLayout(null);

        b1.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b1.setText("NIS");
        jPanel1.add(b1);
        b1.setBounds(10, 40, 80, 30);

        nonis.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        nonis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonisActionPerformed(evt);
            }
        });
        jPanel1.add(nonis);
        nonis.setBounds(120, 40, 190, 30);

        nama.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jPanel1.add(nama);
        nama.setBounds(120, 90, 190, 30);

        b3.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b3.setText("Jenis Kelamin");
        jPanel1.add(b3);
        b3.setBounds(10, 140, 100, 30);

        b4.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b4.setText("Kelas");
        jPanel1.add(b4);
        b4.setBounds(10, 200, 80, 30);

        kelas.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jPanel1.add(kelas);
        kelas.setBounds(120, 200, 190, 30);

        b5.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b5.setText("Tempat Lahir");
        jPanel1.add(b5);
        b5.setBounds(10, 420, 120, 30);

        tptlahir.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jPanel1.add(tptlahir);
        tptlahir.setBounds(120, 420, 190, 30);

        buttonGroup1.add(laki);
        laki.setText("Laki - Laki");
        jPanel1.add(laki);
        laki.setBounds(120, 140, 80, 30);

        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        jPanel1.add(perempuan);
        perempuan.setBounds(210, 140, 90, 30);

        b6.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b6.setText("Email");
        jPanel1.add(b6);
        b6.setBounds(10, 250, 80, 30);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 300, 190, 100);

        b7.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b7.setText("Tanggal Lahir");
        jPanel1.add(b7);
        b7.setBounds(10, 470, 120, 30);

        b8.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b8.setText("Alamat");
        jPanel1.add(b8);
        b8.setBounds(10, 300, 80, 30);

        email.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jPanel1.add(email);
        email.setBounds(120, 250, 190, 30);
        jPanel1.add(tgllahir);
        tgllahir.setBounds(120, 470, 190, 40);

        b10.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        b10.setText("Nama");
        jPanel1.add(b10);
        b10.setBounds(10, 90, 80, 30);

        jPanel5.add(jPanel1);
        jPanel1.setBounds(10, 70, 320, 520);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setLayout(null);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(20, 10, 90, 30);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(120, 10, 90, 30);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);
        clear.setBounds(220, 10, 90, 30);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel2.add(refresh);
        refresh.setBounds(320, 10, 90, 30);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit);
        edit.setBounds(420, 10, 90, 30);

        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel2.add(btnprint);
        btnprint.setBounds(520, 10, 90, 30);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(350, 70, 640, 50);

        jButton1.setFont(new java.awt.Font("Square721 BT", 3, 24)); // NOI18N
        jButton1.setText("EXIT FROM THE PROGRAM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(10, 610, 980, 50);

        labeltanggal.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        labeltanggal.setText("Tanggal");
        jPanel5.add(labeltanggal);
        labeltanggal.setBounds(750, 20, 80, 30);

        labeljam.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        labeljam.setText("Jam");
        jPanel5.add(labeljam);
        labeljam.setBounds(830, 20, 150, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1010, 670);

        setBounds(0, 0, 1025, 707);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(tgllahir.getDate());
        if ("".equals(nonis.getText()) || "".equals(alamat.getText()) || "".equals(kelas.getText()) || "".equals(nama.getText()) || "".equals(email.getText()) || "".equals(tptlahir.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (laki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "INSERT INTO t_siswa VALUES "
                    + "('" + nonis.getText() + "','" 
                    + nama.getText() + "','" 
                    + JK + "','"
                    + kelas.getText() + "','" 
                    +email.getText() + "','" 
                    + alamat.getText() + "','"
                    + tptlahir.getText() + "','" 
                    + tanggal + "')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            String NIS = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                 
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Barisnya Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nama.setText("");
        nonis.setText("");
        kelas.setText("");
        buttonGroup1.clearSelection();
        email.setText("");
        tptlahir.setText("");
        alamat.setText("");
        tgllahir.setDate(null);
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
       selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String tanggal = dateFormat.format(tgllahir.getDate());
        int baris = tabel.getSelectedRow();
        String NIS = tabel.getValueAt(baris, 0).toString();       
        if ("".equals(nonis.getText()) || "".equals(nama.getText()) || "".equals(kelas.getText()) || "".equals(email.getText()) || "".equals(alamat.getText()) || "".equals(tptlahir.getText()) || tanggal.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (laki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET `NIS`='"+nonis.getText()
                    +"',`NamaSiswa`='"+nama.getText()
                    +"',`JenisKelamin`='"+JK 
                    +"',`Kelas`='"+kelas.getText()
                    +"',`Email`='" +email.getText() 
                    +"',`Alamat`='"+alamat.getText()
                    +"',`TempatLahir`='"+tptlahir.getText()
                    +"',`TanggalLahir`='"+tanggal
                    +"' WHERE NIS="+NIS;
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
   
    }//GEN-LAST:event_editActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
       int baris = tabel.getSelectedRow();
        if (baris != -1) {
            nonis.setText(tabel.getValueAt(baris, 0).toString());
            nama.setText(tabel.getValueAt(baris, 1).toString());
            if ("Laki-laki".equals(tabel.getValueAt(baris, 2).toString())) {
                laki.setSelected(true);
            } else {
                perempuan.setSelected(true);
            }
            kelas.setText(tabel.getValueAt(baris, 3).toString());
            email.setText(tabel.getValueAt(baris, 4).toString());
             alamat.setText(tabel.getValueAt(baris, 5).toString());
             tptlahir.setText(tabel.getValueAt(baris, 6).toString());
           SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(tabel.getValueAt(baris, 7).toString());
            } catch (ParseException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }

            tgllahir.setDate(dateFormat);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void nonisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JButton btnprint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kelas;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nonis;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JTextField tptlahir;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
    String kolom[] = {"NIS","Nama Siswa","Jenis Kelamin","Kelas","Email","Alamat","Tempatahir","TanggalLahir"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NIS = rs.getString(1);
                String namaSiswa = rs.getString(2);
                String jenisKelamin = "";
                if ("L".equals(rs.getString(3))) {
                    jenisKelamin = "Laki-laki";
                } else {
                    jenisKelamin = "Perempuan";
                }
                String kelas = rs.getString(4);
                String email = rs.getString(5);
                String alamat = rs.getString(6);
                String tptlahir = rs.getString(7);
                String tgllahir = rs.getString(8);
                String data[] = {NIS,namaSiswa,jenisKelamin,kelas,email,alamat,tptlahir,tgllahir};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(dtm);
    }   
       
    private void setDate() {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltanggal.setText(kal.format(now));
    }

    private void setTime() {
         ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
            Date dt = new Date();
            int nilai_jam = dt.getHours();
            int nilai_menit = dt.getMinutes();
            int nilai_detik = dt.getSeconds();
            
            if (nilai_jam <= 9) {
            nol_jam = "0";
        }
            if (nilai_menit <= 9) {
            nol_menit = "0";
        }
            if (nilai_detik <= 9) {
            nol_detik = "0";
        }
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
            labeljam.setText(jam + ";" + menit + ";" + detik);
        }
    };
        new Timer(100, taskPerformer).start();
    }      
}
